[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; Настройка для использования встроенного USB как Serial (USB-CDC)
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCONFIG_USE_CDC

; Мы всё еще прошиваем через ST-LINK, так как это надежнее
upload_protocol = stlink
debug_tool = stlink

; Скорость для USB-CDC не имеет значения, но оставим для совместимости
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.14